config/routes.rb
Rails.application.routes.draw do
  get 'users/tweets'
  get 'users/new_tweet'
  post 'users/post_tweet'
  get 'users/edit_profile'
  post 'users/update_profile'
  get 'users/suggestions'
  post 'users/add_friend'
  get 'users/search'
  post 'users/search_results'
  get 'users/show_found_user_tweets'
  get 'users/blocked'
  post 'users/block'

  get 'friends/index'
  get 'friends/list'
  delete 'friends/remove_friend'
  get 'friends/messages'
  get 'friends/reply_tweet'
  post 'friends/post_reply_tweet'

  root 'friends#messages'

  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
   end

  def list
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        =  Rails.application.secrets.twitter_consumer_key
      config.consumer_secret     =  Rails.application.secrets.twitter_consumer_secret
      config.access_token        = "#{current_user.oauth_token}"
      config.access_token_secret = "#{current_user.oauth_secret}"
    end

    @friends = client.friends.take(10)
  end

  def remove_friend
    client = Twitter::REST::Client.new do |config|
      config.consumer_key         = Rails.application.secrets.twitter_consumer_key
      config.consumer_secret      = Rails.application.secrets.twitter_consumer_secret
      config.access_token         = "#{current_user.oauth_token}"
      config.access_token_secret  = "#{current_user.oauth_secret}"
    end

    # TODO: Does it work? Need to investigate
    # no error produced but user not removed
    if client.unfollow(params)
      flash[:message] = 'User has been removed'
      redirect_to root_path
    else
      flash[:error] = 'User cannot be removed'
      render 'list'
    end
  end

  def messages
    client = Twitter::REST::Client.new do |config|
      config.consumer_key         = Rails.application.secrets.twitter_consumer_key
      config.consumer_secret      = Rails.application.secrets.twitter_consumer_secret
      config.access_token         = "#{current_user.oauth_token}"
      config.access_token_secret  = "#{current_user.oauth_secret}"
    end

    @messages = client.home_timeline
  end

  def reply_tweet
    @screen_name = '@' + params[:screen_name]
  end

  def post_reply_tweet
    client = Twitter::REST::Client.new do |config|
      config.consumer_key         = Rails.application.secrets.twitter_consumer_key
      config.consumer_secret      = Rails.application.secrets.twitter_consumer_secret
      config.access_token         = "#{current_user.oauth_token}"
      config.access_token_secret  = "#{current_user.oauth_secret}"
    end

    if client.update(params['message'])
      flash[:message] = 'Your reply has been posted'
      redirect_to friends_messages_path
    else
      flash[:error] = 'There was a problem with your message'
      render reply_tweet
    end
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/index.html.erb
<h1>Friends#index</h1>
<p>Find me in app/views/friends/index.html.erb</p>

app/views/friends/list.html.erb
<div class="page-header">
  <h3>My friends</h3>
</div>

<ul class="list-group">
  <% @friends.each do |friend| %>
    <li class="list-group-item">
      <%= friend.name %>
      <%= link_to 'Remove', friends_remove_friend_path(user_id: friend.id), method: :delete, data: { confirm: 'Are you sure?' } %>
      <%= link_to 'Block', users_block_path(user_id: friend.id), method: :post, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>

app/views/friends/messages.html.erb
<div class="page-header">
  <h3>Messages</h3>
</div>

<ul class="list-group">
  <% @messages.each do |msg| %>
    <li class="list-group-item"><%= msg.user.screen_name %> - <%= msg.text %> <%= link_to 'Reply', friends_reply_tweet_path(screen_name: msg.user.screen_name) %></li>
  <% end %>
</ul>

app/views/friends/reply_tweet.html.erb
<%= form_tag(controller: 'friends', action: 'post_reply_tweet', method: 'post') do %>
  <%= label_tag(:message, 'Reply') %><br />
  <%= text_area_tag(:message, @screen_name, size: '44x6') %><br />
  <%= submit_tag('Reply') %>
<% end %>