config/routes.rb
Rails.application.routes.draw do
  get 'users/tweets'
  get 'users/new_tweet'
  post 'users/post_tweet'
  get 'users/edit_profile'
  post 'users/update_profile'
  get 'users/suggestions'
  post 'users/add_friend'
  get 'users/search'
  post 'users/search_results'
  get 'users/show_found_user_tweets'
  get 'users/blocked'
  post 'users/block'

  get 'friends/index'
  get 'friends/list'
  delete 'friends/remove_friend'
  get 'friends/messages'
  get 'friends/reply_tweet'
  post 'friends/post_reply_tweet'

  root 'friends#messages'

  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/user.rb
class User < ActiveRecord::Base

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"] || ""
      user.avatar = auth["info"]["image"] || ""
      user.oauth_token = auth["credentials"]["token"] || ""
      user.oauth_secret = auth["credentials"]["secret"] || ""
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def tweets
    client = Twitter::REST::Client.new do |config|
      config.consumer_key         = Rails.application.secrets.twitter_consumer_key
      config.consumer_secret      = Rails.application.secrets.twitter_consumer_secret
      config.access_token         = "#{current_user.oauth_token}"
      config.access_token_secret  = "#{current_user.oauth_secret}"
    end

    @tweets = client.user_timeline
  end

  def new_tweet
  end

  def post_tweet
    client = Twitter::REST::Client.new do |config|
      config.consumer_key         = Rails.application.secrets.twitter_consumer_key
      config.consumer_secret      = Rails.application.secrets.twitter_consumer_secret
      config.access_token         = "#{current_user.oauth_token}"
      config.access_token_secret  = "#{current_user.oauth_secret}"
    end

    if client.update(params['message'])
      flash[:message] = 'Your message has been posted'
      redirect_to users_tweets_path
    else
      flash[:error] = 'There was a problem with your message'
    end
  end

  def edit_profile
    client = Twitter::REST::Client.new do |config|
      config.consumer_key         = Rails.application.secrets.twitter_consumer_key
      config.consumer_secret      = Rails.application.secrets.twitter_consumer_secret
      config.access_token         = "#{current_user.oauth_token}"
      config.access_token_secret  = "#{current_user.oauth_secret}"
    end

    @user = client.user
  end

  def update_profile
    client = Twitter::REST::Client.new do |config|
      config.consumer_key         = Rails.application.secrets.twitter_consumer_key
      config.consumer_secret      = Rails.application.secrets.twitter_consumer_secret
      config.access_token         = "#{current_user.oauth_token}"
      config.access_token_secret  = "#{current_user.oauth_secret}"
    end

    if client.update_profile(params)
      flash[:message] = 'Profile updated successfully'
      redirect_to root_path
    else
      flash[:error] = 'Profile not updated'
      render edit_profile
    end
  end

  def suggestions
    client = Twitter::REST::Client.new do |config|
      config.consumer_key         = Rails.application.secrets.twitter_consumer_key
      config.consumer_secret      = Rails.application.secrets.twitter_consumer_secret
      config.access_token         = "#{current_user.oauth_token}"
      config.access_token_secret  = "#{current_user.oauth_secret}"
    end

   #@suggestions = []
    #slugs = client.suggestions
    #slugs.each do |sl|
    #  @suggestions << client.suggest_users(sl.slug)
    #end
    #return @suggestions
    #@suggestions = client.suggestions
    # TODO: Problem when getting the list of slugs from above
    @suggestions = client.suggest_users('Sport')
  end

  def add_friend
    client = Twitter::REST::Client.new do |config|
      config.consumer_key         = Rails.application.secrets.twitter_consumer_key
      config.consumer_secret      = Rails.application.secrets.twitter_consumer_secret
      config.access_token         = "#{current_user.oauth_token}"
      config.access_token_secret  = "#{current_user.oauth_secret}"
    end

    if client.follow(params)
      flash[:message] = 'Friend has been created'
      redirect_to friends_list_path
    else
      flash[:error] = 'Friend cannot be added'
      render suggestions
    end
  end

  def search
  end

  def search_results
    client = Twitter::REST::Client.new do |config|
      config.consumer_key         = Rails.application.secrets.twitter_consumer_key
      config.consumer_secret      = Rails.application.secrets.twitter_consumer_secret
      config.access_token         = "#{current_user.oauth_token}"
      config.access_token_secret  = "#{current_user.oauth_secret}"
    end

    @users = client.users(params[:name])

    unless @users.nil?
      flash[:message] = 'The following users have been found'
    else
      flash[:error] = 'Sorry no users match your search criteria'
    end
  end

  def show_found_user_tweets
    client = Twitter::REST::Client.new do |config|
      config.consumer_key         = Rails.application.secrets.twitter_consumer_key
      config.consumer_secret      = Rails.application.secrets.twitter_consumer_secret
      config.access_token         = "#{current_user.oauth_token}"
      config.access_token_secret  = "#{current_user.oauth_secret}"
    end

    @user_tweets = client.user_timeline(user_id: params[:user_id])
  end

  def blocked
    client = Twitter::REST::Client.new do |config|
      config.consumer_key         = Rails.application.secrets.twitter_consumer_key
      config.consumer_secret      = Rails.application.secrets.twitter_consumer_secret
      config.access_token         = "#{current_user.oauth_token}"
      config.access_token_secret  = "#{current_user.oauth_secret}"
    end

    @blocked_users = client.blocked
  end

  def block
    client = Twitter::REST::Client.new do |config|
      config.consumer_key         = Rails.application.secrets.twitter_consumer_key
      config.consumer_secret      = Rails.application.secrets.twitter_consumer_secret
      config.access_token         = "#{current_user.oauth_token}"
      config.access_token_secret  = "#{current_user.oauth_secret}"
    end

    # TODO: Does it really block the user
    # Need to check again as it doesnt' seem to
    if client.block(params)
      flash[:message] = 'This user has been blocked'
      redirect_to users_blocked_path
    else
      flash[:error] = 'Sorry this user cannot be blocked.'
      render friends_list_path
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/blocked.html.erb
<div class="page-header">
  <h3>Blocked users</h3>
</div>

<ul class="list-group">
  <% @blocked_users.each do |bu| %>
    <li class="list-group-item"><%= bu.name %></li>
  <% end %>
</ul>

app/views/users/edit_profile.html.erb
<h3>Edit your profile</h3>

<%= form_tag(controller: 'users', action: 'update_profile', method: 'post') do %>
  <%= label_tag :name, 'Name' %>
  <%= text_field_tag :name, @user.screen_name %><br />
  <%= label_tag :location, 'Location' %>
  <%= text_field_tag :location, @user.location %><br />
  <%= label_tag :description, 'Description' %>
  <%= text_field_tag :description, @user.description %><br />

  <%= submit_tag('Update') %>
<% end %>

app/views/users/new_tweet.html.erb
<%= form_tag(controller: 'users', action: 'post_tweet', method: 'post') do %>
  <%= label_tag(:message, 'Compose new Tweet') %><br />
  <%= text_area_tag(:message, nil, :size => "44x6") %><br /> 
  <%= submit_tag('Update') %>
<% end %>

app/views/users/post_tweet.html.erb
<%= form_tag( controller: 'users', action: 'post_tweet') do %>
  <%= label_tag(:post, 'Compose new tweet') %><br />
  <%= text_area_tag(:post, nil, size: '44x6') %><br />
  <%= submit_tag('Update') %>
<% end %>

app/views/users/search.html.erb
<h2>Find a user</h2>

<%= form_tag(controller: 'users', action: 'search_results', method: 'get') do %>
  <%= label_tag :name, 'Enter user Name' %>
  <%= text_field_tag :name, nil %><br />

  <%= submit_tag 'Search' %>
<% end %>

app/views/users/search_results.html.erb
<h2>The following users have been found</h2>

<ul>
  <% @users.each do |u| %>
    <li><%= u.name %> - <%= u.screen_name %> <%= link_to 'Show posts', users_show_found_user_tweets_path(user_id: u.id) %> </li>
  <% end %>
</ul>

app/views/users/show_found_user_tweets.html.erb
<h2>User messages</h2>

<ul>
  <% @user_tweets.each do |t| %>
    <li><%= t.text %></li>
  <% end %>
</ul>

app/views/users/suggestions.html.erb
<div class="page-header">
  <h3>Suggestions</h3>
</div>

<ul class="list-group">
  <% @suggestions.each do |sug| %>
    <li class="list-group-item"><%= sug.name %> <%= link_to 'Add Friend', users_add_friend_path(uid: sug.id, follow: true), method: 'post'  %></li>
  <% end %>
</ul>

app/views/users/tweets.html.erb
<div class="page-header">
  <h3>My tweets</h3>
</div>

<ul class="list-group">
  <% @tweets.each do |t| %>
    <li class="list-group-item">
      <%= t.text %>
   </li>
  <% end %>
</ul>