config/routes.rb
Rails.application.routes.draw do
  get 'users/tweets'
  get 'users/new_tweet'
  post 'users/post_tweet'
  get 'users/edit_profile'
  post 'users/update_profile'
  get 'users/suggestions'
  post 'users/add_friend'
  get 'users/search'
  post 'users/search_results'
  get 'users/show_found_user_tweets'
  get 'users/blocked'
  post 'users/block'

  get 'friends/index'
  get 'friends/list'
  delete 'friends/remove_friend'
  get 'friends/messages'
  get 'friends/reply_tweet'
  post 'friends/post_reply_tweet'

  root 'friends#messages'

  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yantwicli</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <!-- Fixed navbar -->  
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">YanTwiCli</a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to 'Home', friends_messages_path %></li>
          <% if current_user %>
            <li><%= link_to 'Friends', friends_list_path %></li>
            <li><%= link_to 'Me', users_tweets_path %></li>
            <li><%= link_to 'Tweet', users_new_tweet_path %></li>
            <li><%= link_to 'Edit Profile', users_edit_profile_path %></li>
            <li><%= link_to 'Add Friends', users_suggestions_path %></li>
            <li><%= link_to 'Show All Messages', friends_messages_path %></li>
            <li><%= link_to 'Find a user', users_search_path %></li>
            <li><%= link_to 'Blocked users', users_blocked_path %></li>
            <li><%= link_to 'Sign out', signout_path %></li>
          <% else %>
            <li><%= link_to 'Sign in with Twitter', '/auth/twitter' %></li>
          <% end %>
        </ul>
      </div>  <!--/navbar-header -->
    </div> <!-- /container -->
  </div> <!-- /navbar -->

  <div class="container" role="main">
    <div class="jumbotron">
      <h1>Yet ANother TWItter CLIent</h1>
      <% unless current_user %>
        <p>Please use the login button to login first</p>
      <% else %>
        <p> 
          <% flash.each do |key, value| %>
            <div class='flash' id='<%= key %>'>
              <%= value %>
            </div>
          <% end %>
        </p>
      <% end %>
     </div> <!-- /jumbotron -->
    </div> <!-- /container -->
  </div> <!-- /container -->

  <div class="row">
    <div class="col-sm-3">
    </div>
    <div class="col-sm-6">
      <%= yield %>
    </div>
    <div class="col-sm-3">
    </div>
  </div>

</body>
</html>